[package]
name = "tanoshi"
version = "0.30.0"
edition = "2021"
description = "Tanoshi"
repository = "https://github.com/faldez/tanoshi"
license = "MIT"


[lib]
name = "tanoshi"
path = "src/lib.rs"

[[bin]]
name = "tanoshi"
path = "bin/tanoshi.rs"
test = false
bench = false

[features]
default = ["embed", "server"]
embed = ["rust-embed"]
server = ["axum", "headers", "http", "async-graphql-axum", "tower-http"]

[dependencies]
tanoshi-lib = { path = "../tanoshi-lib" }
tanoshi-vm = { path = "../tanoshi-vm" }
tanoshi-tracker = { path = "../tanoshi-tracker" }
tanoshi-notifier = { path = "../tanoshi-notifier" }
tokio = { version = "1", features = ["full"] }
tokio-stream = { version = "0.1.9", features = ["sync"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
bincode = "1"
async-graphql = { version = "5", features = [
    "apollo_tracing",
    "chrono",
    "dataloader",
    "log",
] }
async-graphql-axum = { version = "5", optional = true }
axum = { version = "0.6", features = ["headers"], optional = true }
headers = { version = "0.3", optional = true }
http = { version = "0.2.5", optional = true }
tower-http = { version = "0.4", features = [
    "cors",
    "compression-br",
    "compression-deflate",
    "compression-gzip",
    "compression-zstd",
], optional = true }
rand = { version = "^0.8" }
log = { version = "*" }
env_logger = "0.10"
jsonwebtoken = "8"
chrono = { version = "0.4", features = ["serde"] }
anyhow = "1"
thiserror = "1"
rust-embed = { version = "6.0", features = [
    "interpolate-folder-path",
], optional = true }
mime_guess = "2"
clap = { version = "4", features = ["derive"] }
bytes = "1"
dirs = "5"
base64 = "0.21"
sqlx = { version = "0.6", features = [
    "runtime-tokio-native-tls",
    "sqlite",
    "chrono",
    "json",
    "migrate",
] }
reqwest = { version = "^0.11.4", features = ["json"] }
futures = "^0.3"
rust-argon2 = "1"
fancy-regex = "0.11"
compress-tools = { git = "https://github.com/faldez/compress-tools-rs", features = [
    "static",
] }
zip = { version = "0.6", default-features = false }
phf = { version = "0.11.0", features = ["macros"] }
human-sort = "^0.2.2"
aes = "0.8"
cbc = "0.1"
once_cell = "^1.8.0"
async-trait = "^0.1.51"
itertools = "0.10.2"
rayon = "1.5"
flume = "0.10.13"
