name: release-cli

on:
  push:
    tags:
      - tanoshi-cli/v[0-9]+.[0-9]+.[0-9]+

jobs:
  build:
    runs-on: ubuntu-20.04
    environment: default
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
      - name: Install deps
        run: sudo apt update && sudo apt upgrade -y && sudo apt install -y libssl-dev libarchive-dev build-essential cmake libicu-dev nettle-dev libacl1-dev liblzma-dev libzstd-dev liblz4-dev libbz2-dev zlib1g-dev libxml2-dev lsb-release wget software-properties-common libwebkit2gtk-4.0-dev curl libgtk-3-dev libappindicator3-dev patchelf librsvg2-dev libpango1.0-dev
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "13.0"
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.69.0
          override: true
      - name: Build tanoshi-cli
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: -p tanoshi-cli --release
        env:
          RUSTFLAGS: "-Clink-arg=-Wl,--allow-multiple-definition"
          LLVM_SYS_130_PREFIX: ${{ env.LLVM_PATH }}
      - name: Copy artifact
        run: |
          mkdir ${{ github.workspace }}/artifact/
          cp ${{ github.workspace }}/target/release/tanoshi-cli ${{ github.workspace }}/artifact/
      - name: Upload Release Asset
        uses: jakejarvis/s3-sync-action@master
        env:
          AWS_S3_BUCKET: tanoshi
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_KEY }}
          AWS_S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
          AWS_REGION: ${{ secrets.S3_REGION }}
          SOURCE_DIR: ${{ github.workspace }}/artifact/
          DEST_DIR: tanoshi-cli/${{ env.RELEASE_VERSION }}
      - name: Upload Release Asset
        uses: jakejarvis/s3-sync-action@master
        env:
          AWS_S3_BUCKET: tanoshi
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_KEY }}
          AWS_S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
          AWS_REGION: ${{ secrets.S3_REGION }}
          SOURCE_DIR: ${{ github.workspace }}/artifact/
          DEST_DIR: tanoshi-cli/latest
